### ISSUE TITLE
Add Build Workflow

### ISSUE THREAD

**Issue by flywire** [Amourspirit/libreoffice_ooodev_ext#5]
See https://github.com/flywire/libreoffice_ooodev_ext/actions/runs/5873986185 - download development build at the bottom. Repo needs refactoring a bit and it creates the wrong PythonPath. Could do something similar to build a production version too.

An `oxt` file is a zip file. You could zip the folder and rename with an `oxt` extension but it seems an action will zip any file without a `zip` extension.

**Comment by Amourspirit** [comment]
## Build

This repo has a custom build process.

I wrote the tooling into this repo to build the extension.

```bash
python -m app build
```

This will build the extension using the current version of `OooDev` that has been installed by poetry.

So when a new version of `OooDev` becomes available the proces is as follows.

Update the version in the `pyproject.toml` file:

```toml
[tool.poetry]
name = "OOO Development Tools Extension"
version = "0.12.2"
```

Run the build command.

```bash
python -m app build
```

Thats it! This will replace the `OooDev.oxt` file in the `dist` folder with the current version.

Note: the `oxt` folder is source files that contain placeholders (tokens) and are copied and modified into a `build` folder during the bulid process.

## Process

This proces is as follows:

- oxt folder contents are copied into build folder
- the `build/pythonpath` gets emptied
- All `OooDev` revelent Packages in the current `.venv/../site-packages` get copied into `build/pythonpath` folder.
- All `__pycache__` folder are clean from `build/pythonpath/**`
- The `build/pytonpath` now get zip into `build/pythonpath.zip` and the `build/pythonpath` folder gets removed
- The `build` folder now get zipped, copied into `dist` folder and renamed to `OooDev.oxt`

See the `src/build.py` to see the steps.

For several reason, internally for the `OooDev.oxt` has a `pythonpath.zip` instead of a `pythonpath` folder.
I use a 'job' see `oxt/job.xcu`, to hook LibreOffice startup and add `pythonpath.zip` to The LibreOffice python path.

Python supports using a zip file as a valid import path.

## Automating with a Workflow

I suppose it is possible to do this for this project but it would be much different then the `yaml` file that was pointed to above.
The workflow would have to incoperate updating (`poetry update`), Update the project toml and then call `python -m app build`.
