### ISSUE TITLE
Installation in openSUSE failed

### ISSUE THREAD

**Issue by yardern** [Amourspirit/libreoffice_ooodev_ext#85]
Thanks for this great extension!

I installed OooDev.oxt v0.45.1 in LibreOffice in openSUSE, got error. Since it is available in Extensions window, I updated it to v0.45.3. Then I got:

**Error while installing extension OOO Development Tools. The error message is: <class 'SyntaxError'>: invalid syntax (py_runner.py, line 454), traceback follows
  File "/usr/lib64/libreoffice/program/pythonloader.py", line 147, in writeRegistryInfo
    mod = self.getModuleFromUrl( locationUrl )
  File "/usr/lib64/libreoffice/program/pythonloader.py", line 100, in getModuleFromUrl
    codeobject = compile( src, encfile(filename), "exec" )

 at /home/abuild/rpmbuild/BUILD/libreoffice-24.2.1.2/pyuno/source/module/pyuno_runtime.cxx:947
The extension will not be installed.**

#####################
I installed ooo-dev-tools in python with sucess, but when I run "from ooodev.loader import Lo", I got errors. Is it because I don't have ooodev extension?

Thanks!

**Comment by Amourspirit** [comment]
hmm ...

Line [454](https://github.com/Amourspirit/libreoffice_ooodev_ext/blob/7e669c5ff19c8b4a78bdbd41c4c954896b556fc6/oxt/py_runner.py#L454) is 

```python
if tk := ctx.ServiceManager.createInstance("com.sun.star.awt.Toolkit"):  # type: ignore
```

The "walrus operator", or more formally known as the assignment expression operator (`:=`), was introduced in Python 3.8, which was released in October 2019. This operator allows you to assign values to variables as part of an expression.

LibreOffice on openSUSE ( is suspect) like Ubuntu use the system python (Windows and Mac us embeded python).
The installer has not changed since your last update. (from v0.45.1 to v0.45.3). It is suprising that such an error would pop up.

There are a few things you can try.
Confirm that LibreOffice us using a version of Python 3.8 or greater. You can use the APSO extension for this or you may see something in the log file.

Logging can be set to debug by going into the Extension Dialog and setting Logging to Debug mode. This can be very helpful with tracking down the issue. If the extension is disabled you may have to enable it and restart LibreOffice.

Uninstall the extension and try installing it again. Will mostly likely try to install `ooo-dev-tools 0.46.0` cause I just published it.

**Comment by yardern** [comment]
Hi Amourspirit,

Thank you very much for the quick action!

I used APSO to print sys.version and got 3.6.15. Print sys.path gave me several python3.6.
I am using LibreOffice v24.2.1.2 which is pretty new.
I don't know how to change python version. I removed python3.6 with "zypper remove python3.6", and it removed LibreOffice completly.

I tried v0.46.0 anyway before I removed python3.6, and got similar error:

Error while installing extension OOO Development Tools. The error message is: <class 'SyntaxError'>: invalid syntax (py_runner.py, line 454), traceback follows
  File "/usr/lib64/libreoffice/program/pythonloader.py", line 147, in writeRegistryInfo
    mod = self.getModuleFromUrl( locationUrl )
  File "/usr/lib64/libreoffice/program/pythonloader.py", line 100, in getModuleFromUrl
    codeobject = compile( src, encfile(filename), "exec" )

 at /home/abuild/rpmbuild/BUILD/libreoffice-24.2.1.2/pyuno/source/module/pyuno_runtime.cxx:947
The extension will not be installed.

**Comment by Amourspirit** [comment]
I am suprised that your installation is using an older python version version (3.6).
Unfortunately `ooo-dev-tools` library only supports Python `3.8` and up.
You can look into updating the python on your system (at your own risk), or use an [FlatPack version of LibreOffice](https://flathub.org/apps/org.libreoffice.LibreOffice) or Try an [AppImage version](https://www.libreoffice.org/download/appimage/)
